---

- name: Ensure config directory present
  file:
    path: "/opt/elasticsearch"
    state: directory
    owner: 1000
    group: 1000
    mode: 0775
    force: yes

- name: Ensure template file is present
  template:
    src: 'elasticsearch.yml'
    dest: '/opt/elasticsearch/elasticsearch.yml'
    owner: 1000
    group: 1000
    mode: 0775
    force: yes

- name: Pull elasticsearch docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    source: pull

- name: Install Elasticsearch using Docker
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /opt/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


- name: Wait for cluster to get ready
  uri:
    url: http://localhost:9200/_cluster/health?pretty
    method: GET
    status_code: 200
    validate_certs: false
  register: result
  retries: 20
  delay: 10
  until: result.status == 200
