---

- name: Ensure config directory present
  file:
    path: "/home/lehar/jeanshell"
    state: directory
    owner: 1000
    group: 1000
    mode: '0775'
    force: yes

- name: Ensure template file is present
  template:
    src: elasticsearch.yml
    dest: /home/lehar/jeanshell/elasticsearch.yml
    owner: 1000
    group: 1000
    mode: '0775'
    force: yes

- name: Pull elasticsearch docker image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    source: pull

- name: Install Elasticsearch using Docker
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
    volumes:
      - /home/lehar/jeanshell/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

- name: Wait for cluster to get ready
  uri:
    url: http://localhost:9200/_cluster/health?pretty
    method: GET
    status_code: 200
    validate_certs: false
  register: result
  retries: 10
  delay: 10
  until: result.status == 200


# ---

# - name: ensure config directory present
#   file:
#     path: "/home/lehar/jeanshell/ansible/roles/elasticsearch"
#     state: directory
#     owner: 1000
#     group: 1000
#     mode: 0775
#     force: yes

# - name: Ensure template file is present
#   template:
#     src: elasticsearch.yml
#     dest: /home/lehar/jeanshell/ansible/roles/elasticsearch/elasticsearch.yml
#     owner: 1000
#     group: 1000
#     mode: 0775
#     force: yes

# - name: pull elasticsearch docker image
#   docker_image:
#     name:  docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#     source: pull

# - name: Install Elasticsearch using Docker
#   docker_container:
#     name: elasticsearch
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#     state: started
#     ports:
#       - "9200:9200"
#         #env:
#         #discovery.type: single-node
#     volumes:
#        - /home/lehar/jeanshell/ansible/roles/elasticsearch/templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
         
# - name: wait for cluster to get ready
#   uri:
#     url: http://localhost:9200/_cluster/health?pretty
#     method: GET
#     status_code: [200]
#     # user: elasticuser
#     # passwrod: elasticpassword
#     validate_certs: false
#   register: result
#   until: result.status == 200
#   retries: 20
#   delay: 10

###################33with network
# ---
# #- name: Create Docker network
#   # docker_network:
#   #   name: my-network

# - name: ensure config directory present
#   file:
#     path: "/home/lehar/jeanshell/ansible/roles/elasticsearch"
#     state: directory
#     owner: 1000
#     group: 1000
#     mode: 0775
#     force: yes

# - name: ensure template file is present
#   template:
#     src: elasticsearch.yml
#     dest: /home/lehar/jeanshell/ansible/roles/elasticsearch/elasticsearch.yml
#     owner: 1000
#     group: 1000
#     mode: 0775
#     force: yes

# - name: pull elasticsearch docker image
#   docker_image:
#     name:  docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#     source: pull

# - name: Install Elasticsearch using Docker
#   docker_container:
#     name: elasticsearch
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#     state: started
#     ports:
#       - "9200:9200"
#         #env:
#         #discovery.type: single-node
#     volumes:
#        - /home/lehar/jeanshell/ansible/roles/elasticsearch/templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
#     # networks:
#     #    - name: my-network
         
# - name: wait for cluster to get ready
#   uri:
#     url: http://localhost:9200/_cluster/health?pretty
#     method: GET
#     status_code: [200]
#     # user: elasticuser
#     # passwrod: elasticpassword
#     validate_certs: false
#   register: result
#   until: result.status == 200
#   retries: 20
#   delay: 10







# ---

#   - name: Deploy Elasticsearch with Docker
#     file:
#       path: "/home/lehar/ansible_elk/roles/elasticsearch"
#       state: directory
#       owner: 1000
#       group: 1000
#       mode: "0775"
#       force: yes

#   - name: Ensure template file is present
#     template:
#       src: elasticsearch.yml
#       dest: /home/lehar/ansible_elk/roles/elasticsearch/templates/elasticsearch.yml
#       owner: 1000
#       group: 1000
#       mode: "0775"
#       force: yes

#   - name: Pull Elasticsearch Docker image
#     docker_image:
#       name: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#       source: pull

#   - name: Install Elasticsearch using Docker
#     docker_container:
#       name: elasticsearch
#       image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
#       state: started
#       ports:
#         - "9200:9200"  # HostPort:ContainerPort
#       volumes:
#         - /home/lehar/ansible_elk/roles/elasticsearch/templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

#   - name: Wait for cluster to get ready
#     uri:
#       url: http://localhost:9200/_cluster/health?pretty
#       method: GET
#       status_code: [200]
#       validate_certs: false
#     register: result
#     until: result.status == 200
#     retries: 20
#     delay: 10
